name: Run tests

on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
         python-version: 3.11
      - name: Install requirements
        run: |
              python -m pip install -r ./requirements.txt
      - name: run tests
        run: |
              ./project/pipeline.sh
