name: Run tests

on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
         python-version: 3.11
      - name: Install requirements
        run: |
              pip install -r requirements.txt
      - name: run tests
        uses: ./project/pipeline.sh
